---
- name: intoinfinity VPC setup
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_variables

    - name: Creating VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{CIDR}}"
        region: "{{region}}"
        tenancy: default
        tags:
          Name: intoinfinity-vpc
        state: present
      register: vpcout

    # - debug:
    #     var: vpcout
#Public Subnet A for VPC
    - name: Create PublicSubnetA
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone[0]}}"
        cidr: "{{PublicSubnetA}}"
        region: "{{region}}"
        map_public: yes
        tags:
          Name: PublicSubnetA
      register: PublicSubnetA
#Public Subnet B for VPC
    - name: Create PublicSubnetB
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone[1]}}"
        cidr: "{{PublicSubnetB}}"
        region: "{{region}}"
        map_public: yes
        tags:
          Name: PublicSubnetB
      register: PublicSubnetB
#Public Subnet C for VPC
    - name: Create PublicSubnetC
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone[2]}}"
        cidr: "{{PublicSubnetC}}"
        region: "{{region}}"
        map_public: yes
        tags:
          Name: PublicSubnetC
      register: PublicSubnetC

#Private Subnet A for VPC
    - name: Create PrivateSubnetA
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone[0]}}"
        cidr: "{{PrivateSubnetA}}"
        region: "{{region}}"
        tags:
          Name: PrivateSubnetA
      register: PrivateSubnetA
#Private Subnet B for VPC
    - name: Create PrivateSubnetB
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone[1]}}"
        cidr: "{{PrivateSubnetB}}"
        region: "{{region}}"
        tags:
          Name: PrivateSubnetB
      register: PrivateSubnetB
#Private Subnet C for VPC
    - name: Create PrivateSubnetC
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{vpcout.vpc.id}}"
        az: "{{zone[2]}}"
        cidr: "{{PrivateSubnetC}}"
        region: "{{region}}"
        tags:
          Name: PrivateSubnetC
      register: PrivateSubnetC

# Internet Gateway for public subnet
    - name: Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{vpcout.vpc.id}}"
        region: "{{region}}"
        state: present
        tags:
          Name: intoinfinity-igw
      register: igw

    - debug:
        var: igw

# Creating Route Table

    - name: Set up public subnet route table
      ec2_vpc_route_table:
        vpc_id: vpc-1245678
        region: us-west-1
        tags:
          Name: Public-RT
        subnets:
          - "{{ PublicSubnetA.subnet.id }}"
          - "{{ PublicSubnetB.subnet.id }}"
          - "{{ PublicSubnetC.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
        gateway_id: "{{ igw.gateway_id }}"
      register: public_route_table
      