---
- name: intoinfinity VPC setup
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_variables

    - name: Creating VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{CIDR}}"
        region: "{{region}}"
        tenancy: default
        tags:
          Name: intoinfinity-vpc
        state: present
      register: vpcout

    # - debug:
    #     var: vpcout
#Public Subnet A for VPC
    - name: Create PublicSubnetA
      ec2_vpc_subnet:
        state: present
        vpc_id: vpcout.vpc.id
        cidr: PublicSubnetA
        region: "{{region}}"
        az: zone1
        map_public: yes
        tags:
          Name: PublicSubnetA
      register: PublicSubnetA
#Public Subnet B for VPC
    - name: Create PublicSubnetB
      ec2_vpc_subnet:
        state: present
        vpc_id: vpcout.vpc.id
        cidr: PublicSubnetB
        region: "{{region}}"
        az: zone2
        map_public: yes
        tags:
          Name: PublicSubnetB
      register: PublicSubnetB
#Public Subnet C for VPC
    - name: Create PublicSubnetC
      ec2_vpc_subnet:
        state: present
        vpc_id: vpcout.vpc.id
        cidr: PublicSubnetC
        region: "{{region}}"
        az: zone3
        map_public: yes
        tags:
          Name: PublicSubnetC
      register: PublicSubnetC

#Private Subnet A for VPC
    - name: Create PrivateSubnetA
      ec2_vpc_subnet:
        state: present
        vpc_id: vpcout.vpc.id
        cidr: PrivateSubnetA
        region: "{{region}}"
        az: zone1
        tags:
          Name: PrivateSubnetA
      register: PrivateSubnetA
#Private Subnet B for VPC
    - name: Create PrivateSubnetB
      ec2_vpc_subnet:
        state: present
        vpc_id: vpcout.vpc.id
        cidr: PrivateSubnetB
        region: "{{region}}"
        az: zone2
        tags:
          Name: PrivateSubnetC
      register: PrivateSubnetB
#Private Subnet C for VPC
    - name: Create PrivateSubnetC
      ec2_vpc_subnet:
        state: present
        vpc_id: vpcout.vpc.id
        cidr: PrivateSubnetC
        region: "{{region}}"
        az: zone3
        tags:
          Name: PrivateSubnetC
      register: PrivateSubnetC
