---
- name: intoinfinity VPC setup
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Import VPC variables
      include_vars: vars/vpc_variables

    - name: Creating VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{CIDR}}"
        region: "{{region}}"
        tenancy: default
        tags:
          Name: intoinfinity-vpc
        state: present
      register: vpcout

    - debug:
        var: vpcout
