---
- name: Creating Key Pair
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

        - name: Sample EC2 key-pair
          ec2_key:
                  name: samplekey
                  region: us-east-2

          register: keyout
        - debug:
                  var: keyout

        - name: Store Log in key
          copy:
                  content: "{{keyout.key.private_key}}"
                  dest: ./samplekey.pem

          when: keyout.changed
